token:
  expiration:
    time: 8640000
  secret: '{cipher}AQBKF1KNFN5A2Prsr0orUJ6/lYQe4XxHzqn+5q0cvNYOOCeOVdpbwPb3gZYQexqeryQoOlhEdOe33lNw080c2Zcoz7Vdmb1eEXtzgQwG39i6KqWP3QIT+FUKocecLbkqixj+nqCCcQYkc/FMxufhhIYj497r/pK2v+tPaQq3YC9cJiTVPDJVD8VIUwy/6CvVM1m9k8pHh+R6Edi2aMcWEmW41Lxsxh5qHx7jEbEcWpoiBUrTVZ/JeBk292jITT83mLuO+biFt5LHyzSKWlyP7xHZ+MyRhxYGovSHTROJLN6wZwgk0SFRXLbxynMa4c6YSo46mJxSgBQJ9qy+1reCzxGTgjvXxoyFdSJBa6u5D5dzPlTHfJaapFBkMolq/xcenAh5HBwLj4jevAFCEAEnj1Li'
